export const CommonJson = {
    "Delete": "Xóa",
    "Add": "Thêm",
    "Create": "Tạo",
    "Edit": "Sửa",
    "Done": "Xong",
    "Month": "Tháng",
    "Cancel": "Hủy",
    "Complete": "Hoàn thành",
    "Completed": "Đã hoàn thành",
    "Overtime": "Đã quá giờ",
    "UpComing": "Sắp diễn ra",
    "Confirm": "Đồng ý",
    "LogOut": "Đăng xuất",
    "Save": "Lưu",
    "Reset": "Đặt lại",
    "Male": "Nam",
    "Female": "Nữ",
    "TakePhoto": "Chụp ảnh",
    "UploadPhoto": "Tải ảnh lên",
    "Title": "Tiêu đề",
    "No": "Không",
    "Yes": "Có",
    "Assign": 'lớp được giao',
    "PostAssigned": 'Bài đã giao',
    "ChooseCurriculum": 'Chọn giáo trình',
    "AssignItem": 'Giao bài',
}