const API = {
  header: {
    'Content-Type': 'application/json',
    jwt_token:
      'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjEiLCJ1c2VybmFtZSI6ImFkbWluIiwidGltZV9sb2dpbiI6MTU3ODkwNzQyM30.CFZyO9a-qBmyI8Q25AqGNd1nxWn1SO5TMC_yBxjgWCA',
    'x-api-key': '8c3a30506d9633a8b202cb5a91873efa',
    Authorization: 'Basic Z2VrX2FkbWluOmdla19hZG1pbl9wYXNzd29yZA==',
  },
  domain: 'https://service.sundayenglish.com/',
  image_base_url: 'https://service.sundayenglish.com/',
  baseurl: 'https://service.sundayenglish.com/api/',
  test_push_notification: 'api_user/test_notify',
  history_masterUnit: 'student/api_student_lesson/master_unit_history',
  getGradeNew: 'api_login/grade',
  postFileGuide: 'api_resources/upload_guide',
  login_Id_Pass: 'api_login/check',
  api_student: 'api_student/data_learn_screen_v2',
  api_student_vocab: 'api_student/student_vocab',
  baseurl_2: 'https://order.sundayenglish.com/api/',
  baseurl_pay: 'https://oauth2.sundayenglish.com/api/',
  getExercisesDelivered: 'api_class/class_homework?class_id=',
  getCourse: 'api_curriculum/courses_name',
  getMarkWritting: (id, library, exercise_type) =>
    `student/api_homework/homework_detail?user_exercise_id=${id}&library=${library}&exercise_type=${exercise_type}`,
  getCourseDetail: (classId, exerciseId) =>
    `api_class/class_homework_detail?class_id=${classId}&exercise_id=${exerciseId}`,
  getListStudents: 'api_class/students?limit=10&offset=0&class_id=1',
  getCourseManager: 'api_curriculum/courses_name',
  getCourseManagerDetail: 'api_curriculum/course?id=',
  studentLesson: (id, class_id) =>
    `student/api_student_lesson/lesson?id=${id}&class_id=${class_id}`,
  saveLogLearning: 'api_log_learning/save_log_learning',
  save_homework: 'student/api_homework/save_homework',
  listClassOffline: 'api_class_offline/my_classes',
  listStudentByClassId: 'api_class_offline/class?id=',
  createClass: 'api_class_offline/class',
  getLessonHistory: 'student/api_student_lesson/lesson_history',
  getMasterUnitLessonHistory: (id, type) =>
    `api_log_learning/master_unit_utilize?id=${id}&type=${type}`,
  getCurriculumCourses: 'api_curriculum/courses_name',
  updateClassName: 'api_class_offline/class',
  attendance: 'api_class_offline/roll_up',
  classExam: 'api_class_offline/class_exam_card?class_id=',
  deleteScoreBr: 'api_class_offline/class_exam_card',
  saveExam: 'api_class_offline/exam_card',
  examCardDetail: 'api_class_offline/exam_card_detail?card_id=',
  updateExamCard: 'api_class_offline/exam_card',
  addNewStudent: 'api_class_offline/student',
  detailsAttendance: 'api_class_offline/roll_up?id=',
  getExamClass: id =>
    'api_class/class_homework?class_id=' +
    id +
    '&skill[]=speaking&skill[]=writing',
  getDetailsExamClass: (id, exercise_id) =>
    'api_class/home_work_detail?class_id=' + id + '&exercise_id=' + exercise_id,
  getDetailsExerciseClass: (id, exercise_id, library) =>
    'api_class/home_work_detail?class_id=' +
    id +
    '&exercise_id=' +
    exercise_id +
    '&library=' +
    library,
  getExerciseDetail: (exercise_id, library, exercise_type) =>
    'student/api_homework/homework_detail?user_exercise_id=' +
    exercise_id +
    '&library=' +
    library +
    '&exercise_type=' +
    exercise_type,
  EditClasscurriculum: 'api_class/class_curriculum_edit',
  requestAmica: 'api_class/request_amica',
  acceptAmicaResult: 'api_class/accept_amica_result',
  homeworkDetail: 'student/api_homework/homework_detail?user_exercise_id=',
  saveResultHomework: 'api_class/save_result_homework',
  CourseManager: 'api_class/class_curriculum?curriculum_id=',
  Classcurriculum: 'api_class/class_curriculum',
  loginFacebook: 'api_login/facebook_auth',
  loginGoogle: 'api_login/google_auth_v2',
  loginApple: 'api_login/apple_auth',
  getExam: id => 'student/api_exam/exam?id=' + id,
  saveLogExam: 'api_log_learning/save_exam',
  loadExamResult: 'student/api_student_lesson/load_exam_result?id=',
  getMiniTest: id => 'student/api_student_lesson/data_mini_test?id=' + id,
  getMiniTestData: id => 'api_lesson/data_mini_test?id=' + id,
  loadMiniTestResult: 'student/api_student_lesson/load_mini_test_result?id=',
  remindStudent: `api_inbox/remind`,
  urlAvatar: `https://setest.gkcorp.com.vn`,
  addWishList: 'api_wish_list/my_wish_list',
  removeWishList: 'api_wish_list/my_wish_list',
  listWishList: 'api_wish_list/my_wish_list?user_id=',
  getWishList: `api_wish_list/my_wish_list`,
  confirmRelationship: `api_relationship/confirm_relationship`,
  sendRequest: `api_relationship/send_request`,
  getListChild: `api_parent/list_child`,
  teacherLesson: 'api_lesson/lesson?id=',
  register: `api_register/register`,
  checkScore: 'api_log_learning/check_score',
  addInfo: `api_user/user`,
  forgetPassword: `api_login/forget_password`,
  getStudentMyClass: 'api_class/my_classes',
  giveHomework: 'api_class/give_homework',
  getMyGiveHomework: 'api_user_exercise/my_give_homework',
  getDiaryStudent: idStudent =>
    `student/api_homework/student_summary_report?student_id=${idStudent}`,
  feedBack: 'api_feedback/feedback',
  myHomework: 'api_user_exercise/my_homework',
  getResource: (id, class_id) =>
    `api_resources/my_resource?id=${id}&class_id${class_id}`,
  getLessonMyHomework: id => `api_lesson/lesson?id=${id}`,
  getLessonMyHomework2: id => `api_lesson/homework?user_exercise_id=${id}`,
  getLessonMasterUnit: (id, type) =>
    `student/api_student_lesson/looking_back_detail?id=${id}&type=${type}`,
  saveMasterUnit: 'api_log_learning/learning_improvement',
  getAttendance: 'api_class_offline/my_classes',
  settingUser: 'api_user/load_setting_notify',
  saveSettingUser: '/api_user/save_setting_notify',
  getStudyGuide: 'api_resources/my_resources',
  uploadResource: 'api_resources/upload',
  api_inbox: 'api_inbox/inbox',
  api_inbox_detail: 'api_inbox/inbox_detail',
  api_inbox_system: 'api_inbox/inbox_system',
  list_contact: 'api_inbox/list_contact',
  send: 'api_inbox/send',
  remind: 'api_inbox/remind',
  getLicenseOwned: 'license/license_owned',
  getLicense: 'license/license/',
  getDetailsLicense: 'license/license_by_id/',
  addOrderLicense: 'order/add_order',
  activeLicenseCode: 'license/active_license_code',
  listOrder: 'order/list_order?student_id=',
  getCriteria: idExercise =>
    `api_class/load_exercise_criteria?exercise_id='${idExercise}`,
  getDetailsWorkDelivered: (id, exercise_id) =>
    'api_class/class_homework_detail?class_id=' +
    id +
    '&exercise_id=' +
    exercise_id,
  updateCriteria: 'api_class/writing_criteria',
  saveMarkWriting: 'api_class/save_mark_writing',
  aiCheckWriting: 'api_class/ai_check_writing',
  getMockTest: (grade_id, address_id) =>
    `student/api_exam/mock_test?grade_id=${grade_id}&address_id=${address_id}`,
  getDetailsMockTest: 'student/api_exam/mock_test_info?mock_test_id=',
  mockTestHistory: (grade_id, address_id) =>
    `student/api_exam/mock_test_history?grade_id=${grade_id}&address_id=${address_id}`,
  getListAddress: 'student/api_exam/list_address',
  getGrade: 'api_user/grade',
  search_lesson: 'api_curriculum/search_lesson?skill=',
  topic: '&topic=',
  recordingFile: '/student/api_student_lesson/recording_file?file',
  Grade: 'api_user/grade',
  Data_request: 'api_class/class_member_request?class_id=',
  GetClassMember: 'api_class/students',
  Reject_member_request: 'api_class/reject_member_request',
  Accept_member_request: 'api_class/accept_member_request',
  send_request_add_student: 'api_class/add_student',
  // Rccept_member_request: 'api_class/accept_member_request',
  startMockTest: 'student/api_exam/start_mock_test',
  // Rccept_member_request: 'api_class/accept_member_request',
  saveMarkExercise: 'api_class/save_mark_exercise',
  api_profile: 'api_profile/profile?id=',
  checkUserCode: 'api_user/code?user_code=',
  makeRelationship: 'api_user/make_relationship',
  student_assessment: 'api_student/student_assessment?student_id=',
  learning_history: 'api_student/learning_history?student_id=',
  student_log_learning: 'api_student/student_log_learning?',
  student_log_learning_by_teacher: 'api_student/log_learning_by_date?',
  student_log_learning_status: 'api_student/log_learning_status?',
  my_classes: 'api_class/my_classes',
  lessons_by_skill: id =>
    'student/api_student_curriculum/lessons_by_skill?unit_id=' + id,
  map_unit: id => 'student/api_student_curriculum/map_unit?class_id=' + id,
  saveMockTest: 'student/api_exam/save_mock_test',
  mockTestHistoryDetail:
    'student/api_exam/mock_test_history_detail?user_exam_result_id=',
  saveDefaultLesion: 'api_student/save_default_curriculum',
  compare_record: 'student/api_student_lesson/compare_recording_file',
  listAchivement: 'api_student/student_assessment?student_id=',
  offlineachievements: 'api_class_offline/achievements',
  MyClass: 'api_class/my_classes',
  getRoomIDFrom2User: 'api_inbox/check_room?to_user_id=',

  getPlan: 'API_schedule/get_all_schedule?',
  getPlanByMonth: 'API_schedule/schedule_status',
  createPlan: 'API_schedule/insert_schedule',
  deletePlan: 'API_schedule/delete_schedule',
  editPlan: 'API_schedule/edit_schedule',
  editProfile: 'api_user/user/',
  addLessonTimeTable: 'API_schedule_lock/schedule_lock',
  getLessonTimeTable: 'API_schedule_lock/get_all_schedule',
  resetLessonTimeTable: 'API_schedule_lock/reset_schedule',
  updateScheduleConfig: 'API_schedule_lock/schedule_config',
  validateRelationship: 'api_relationship/confirm_relationship',
  requestRelationship: 'api_relationship/send_request',
  updateAvatar: 'api_user/update_avatar',
  student_grammar: id => 'student/api_student_lesson/lesson?id=' + id,
  listGradle: 'api_user/grade',
  CurriculumSunday: type => 'api_curriculum/courses_name?type=' + type,
  detailCurrilum: id => 'api_curriculum/course?id=' + id,
  favoriteCurriculum: 'api_wish_list/my_wish_list',
  filterCurriculum: 'api_curriculum/search_lesson?',
  appLanguage: 'api_login/app_language?lang=vi',
  student_grammar: id => 'student/api_student_lesson/lesson?id=' + id,
  ManageAssign: 'api_class/class_homework_v2',
  DetailManageAssign: 'api_wish_list/wish_list_history?exercise_id=',
  ListWordScheduleYear: 'API_schedule_year/list_schedule_year?year=',
  UpdateSchedule: 'API_schedule_year/edit_schedule_year',
  CreateSchedule: 'API_schedule_year/create_schedule_year',
  ClassOnline: 'api_class/classes',
  CreateClass: 'api_class/class',
  UpdateClass: 'api_class/class_edit',
  DelClass: 'api_class/class',
  ReportByClass: 'api_student/report_overview_class',
  StudentReport: 'api_student/report_overview_student',
  ManagentAssign: 'api_class/class_homework',
  remindAll: 'api_inbox/remind_all',
  SaveProject: 'student/api_student_lesson/save_project',
  getProvinces: 'api_category/provinces?country_code=vn',
  getDistricts: 'api_category/districts',
  getSchool: 'api_category/schools',
  checkEmail: 'api_register/check_email',
  resend_active_email: 'api_register/resend_active_email',
  mark_system_seen: 'api_inbox/mark_system_seen',
  current_version: 'base_api/current_version',
  ignore_version: 'base_api/ignore_version',
  logout: 'api_user/logout',
  deleteAcc: 'api_user/delete',
  getTopSym: 'api_student/ranking?type=total',
  getHistoryRecoder: 'student/api_student_lesson/history_log_ai_speaking',
  getProductionList: 'package/available_package_list',
  package: 'package',
  checkBillCode: 'payment/validate',
  verify_packet: 'package/verify_packet',
  verify_code: 'package/get_confirmation_code',
  active_package: 'package/active',
  history_package: 'payment/history_payment',
  check_version: 'api_login/app_version',
  deleteScorePage: 'api_class_offline/roll_up',
  send_code_zalo: 'teacher/verify_auth',
  register_teacher: 'teacher/register',
  load_placement_test: 'student/api_rootlessness/placement_test_check',
  getCalenderList: 'student/rl_001',
  setCalenderStudy: 'student/api_rootlessness/config_set_day_learn',
  getProgram: 'student/rl_005',
  setProgram: 'student/rl_006',
  getSuggest: 'student/rl_003',
  getSettingAss: 'api_assignment/setting_default',
  getLessonByCapacity: 'api_assignment/capacity',
  getLessonByRequest: 'api_assignment/request',
  postLessonAss: 'api_assignment/assign_homework',
  getVocabByClass: 'api_student/student_vocab_by_class',
  activeByCode: 'package/active_by_code',
  // Parent
  getListChildren: 'parent/api_child/my_children',
  deleteChildAction: 'parent/api_actions/invitation_delete',
  getListPendingChildren: 'parents/children_sublist_waiting',
  getInforStudent: 'parents/view_info_student',
  associateStudent: 'parents/linked_children',
  reportExercise: 'parent/api_child/report_exercise?student_id=',
  reportManageExercise: 'parent/api_child/exercise_parent?student_id=',
  listExerciseStudentAClass:
    'parent/api_user_exercise/list_exercise_graded_bystudentid',
  getDataAvgChild: 'parent/api_user_exercise/average_score_exercise',
  listExerciseMarked:
    'parent/api_user_exercise/list_exercise_graded_bystudentid',
  reportTimeStudyMonth: 'parent/api_child/report_study_month?student_id=',
  reportTimeStudyWeek: 'parent/api_child/study_week_month?student_id=',
  reportExerciseLearned:
    'parent/api_user_exercise/user_exercise_statistic?student_id=',
  reportWordLearned:
    'parent/api_user_exercise/user_vocab_statistic?student_id=',
  getDataAvgSkills: 'parent/api_user_exercise/average_score_skill',
  getSettingParent: 'parent/api_user/load_setting_app',
  postSendRqChild: 'parent/api_actions/invitation_connect',
  getListExerciseAssigned:
    'parent/api_user/api_user_exercise/class_homework_v2',
  manageAssignParent: 'parent/api_user/api_user_exercise/class_homework_v2',
  getListClassesChild: 'parent/api_class/my_classes',
  getListExerciseClass: 'parent/api_user_exercise/my_homework',
};
export default API;
