import {StyleSheet} from 'react-native';
import SmartScreenBase from '../base/SmartScreenBase';

const smartScreenHeight = SmartScreenBase.smPercenHeight;

export default styles = StyleSheet.create({
    container: {
        flex: 1,
        marginTop: smartScreenHeight * 5,
    },
    inner: {
        flex: 1,
        paddingHorizontal: smartScreenHeight * 3,
    },
    _tc_tt_d: {
        height: SmartScreenBase.smPercenHeight * 7,
        backgroundColor: '#017ca4',
        borderRadius: SmartScreenBase.smPercenWidth * 5,
        justifyContent: 'center',
        alignItems: 'center',
    },
    _tc_tt_d_2: {
        height: SmartScreenBase.smPercenHeight * 6,
        backgroundColor: '#fff',
        borderRadius: SmartScreenBase.smPercenWidth * 100,
        justifyContent: 'center',
        paddingHorizontal: SmartScreenBase.smPercenWidth * 5,
    },
    text: {
        fontSize: SmartScreenBase.smFontSize * 45,
        fontWeight: 'bold',
        color: '#fff',
    },
    _v_tc_tt_d: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        width: '100%',
    },
    _v_f: {
        flex: 1,
        backgroundColor: '#ffffff80',
        borderRadius: SmartScreenBase.smPercenWidth * 5,
        justifyContent: 'center',
        alignItems: 'center',
    },
    _v_f_1: {
        flex: 1,
        backgroundColor: '#ffffff',
        borderRadius: SmartScreenBase.smPercenWidth * 5,
        justifyContent: 'center',
        alignItems: 'center',
    },
    _v_c: {
        width: '100%',
        height: SmartScreenBase.smPercenHeight * 41,
        paddingHorizontal: SmartScreenBase.smPercenWidth * 2.5,
        marginTop: SmartScreenBase.smPercenWidth * 2.5,
    },
    _v_c_f: {
        width: '100%',
        height: SmartScreenBase.smPercenHeight * 15,
        paddingHorizontal: SmartScreenBase.smPercenWidth * 2.5,
        marginTop: SmartScreenBase.smPercenWidth * 2.5,
    },
    _v_c_f_h: {
        flex: 1,
        backgroundColor: '#ffffff80',
        borderRadius: SmartScreenBase.smPercenWidth * 5,
        alignItems: 'center',
        justifyContent: 'center',
    },
    _v_c_f_c: {
        height: '95%',
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
    },
    _v_c_2: {
        marginTop: SmartScreenBase.smPercenHeight * 5,
        marginBottom: SmartScreenBase.smPercenHeight * 5,
        justifyContent: 'center',
        paddingHorizontal: SmartScreenBase.smPercenWidth * 10,
    },
    _v_c_3: {
        marginTop: SmartScreenBase.smPercenHeight * 3,
        backgroundColor: '#fff',
        borderTopRightRadius: SmartScreenBase.smPercenWidth * 5,
        borderTopLeftRadius: SmartScreenBase.smPercenWidth * 5,
    },
    _footer: {
        paddingHorizontal: SmartScreenBase.smPercenWidth * 10,
        paddingTop: SmartScreenBase.smPercenWidth * 10,
        paddingBottom: SmartScreenBase.smPercenWidth * 5,
    },
    _footer_2: {
        height: SmartScreenBase.smPercenHeight * 10,
        justifyContent: 'space-around',
        // alignItems: 'center',
        flexDirection: 'row',
    },
    _btn: {
        width: SmartScreenBase.smPercenWidth * 40,
        height: SmartScreenBase.smPercenHeight * 6,
        borderRadius: SmartScreenBase.smPercenWidth * 40,
        backgroundColor: '#00283a',
        justifyContent: 'center',
        alignItems: 'center',
    },
    _img: {
        width: SmartScreenBase.smPercenWidth * 40,
        height: SmartScreenBase.smPercenHeight * 10,
        position: 'absolute',
        top: -SmartScreenBase.smPercenHeight * 5,
        left: SmartScreenBase.smPercenWidth * 5,
    },
    centeredView: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#00000080',
        paddingHorizontal: SmartScreenBase.smPercenWidth * 10,
    },
    modalView: {
        width: SmartScreenBase.smPercenWidth * 80,
        height: SmartScreenBase.smPercenHeight * 50,
        backgroundColor: '#fdf1f6',
        borderRadius: SmartScreenBase.smPercenWidth * 5,
        justifyContent: 'center', alignItems: 'center',
    },
    _b_v: {
        height: SmartScreenBase.smPercenHeight * 33,
        width: SmartScreenBase.smPercenWidth * 75,
        borderWidth: 1,
        borderRadius: SmartScreenBase.smPercenWidth * 3,
        borderColor: '#7f7f7f',
    },
    _b_v_2: {
        height: SmartScreenBase.smPercenHeight * 10,
        borderRadius: SmartScreenBase.smPercenWidth * 3,
        justifyContent: 'space-around',
        alignItems: 'center',
        flexDirection: 'row',
        width: '100%',
    },
    _btnModal: {
        width: SmartScreenBase.smPercenWidth * 30,
        height: SmartScreenBase.smPercenHeight * 6,
        borderRadius: SmartScreenBase.smPercenWidth * 3,
        justifyContent: 'space-around',
        alignItems: 'center',
    },
    _c_t_i: {
        width: '100%',
        padding: SmartScreenBase.smPercenWidth * 5,
        fontSize: SmartScreenBase.smFontSize * 50,
        height: SmartScreenBase.smPercenHeight * 30,
    },
    _v_m_t: {
        width: SmartScreenBase.smPercenWidth * 80,
        backgroundColor: '#fdf1f6',
        borderRadius: SmartScreenBase.smPercenWidth * 3,
        justifyContent: 'center',
        alignItems: 'center',
    },
    _v_btn_t: {
        width: SmartScreenBase.smPercenWidth * 30,
        height: SmartScreenBase.smPercenHeight * 6,
        borderRadius: SmartScreenBase.smPercenWidth * 3,
        backgroundColor: '#00283a',
        justifyContent: 'center',
        alignItems: 'center',
    },
    _v_b_t: {
        height: SmartScreenBase.smPercenHeight * 15,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'absolute',
        bottom: 0,
        width: '100%',
    },
    _v_btn_t_c: {
        width: SmartScreenBase.smPercenWidth * 40,
        height: SmartScreenBase.smPercenHeight * 6,
        borderRadius: SmartScreenBase.smPercenWidth * 40,
        backgroundColor: '#00283a',
        justifyContent: 'center',
        alignItems: 'center',
    },
    _v_a_b: {
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: SmartScreenBase.smPercenHeight,
        height: SmartScreenBase.smPercenHeight * 6,
        width: SmartScreenBase.smPercenWidth * 70,
        borderRadius: SmartScreenBase.smPercenWidth * 2,
        backgroundColor: '#e6e7e8',
    },
    _v_a_b_t: {
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: SmartScreenBase.smPercenHeight,
        width: SmartScreenBase.smPercenWidth * 70,
    },
    _v_a_b_t_c: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        justifyContent: 'space-between',
        width: '100%',
    },
    _b_t_n_s: {
        justifyContent: 'center',
        alignItems: 'center',
        width: SmartScreenBase.smPercenWidth * 30,
        height: SmartScreenBase.smPercenHeight * 5,
        backgroundColor: '#ed8a22',
        borderRadius: SmartScreenBase.smPercenWidth * 2,
    },
    _t_s: {
        fontSize: SmartScreenBase.smFontSize * 45,
        fontWeight: 'bold',
        color: '#fff',
    },
    _img_2: {
        width: SmartScreenBase.smPercenWidth * 10,
        height: SmartScreenBase.smPercenWidth * 10,
        position: 'absolute',
        top: -SmartScreenBase.smPercenWidth * 5,
        right: SmartScreenBase.smPercenWidth * 5,
    },
    modalView_2: {
        width: SmartScreenBase.smPercenWidth * 80,
        backgroundColor: '#fdf1f6',
        borderRadius: SmartScreenBase.smPercenWidth * 5,
        justifyContent: 'center', alignItems: 'center',
    },
});
